In [1]:
import numpy as np

In [3]:
# create or initialise ararys
a = np.array([1,2,3,4,5])  # giving a list
print(a)
print(type(a))
print(a.shape)  # shape/dimension returns a tuple -> (5,) which means this is a linear array

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
b = np.array([[1],[2],[3],[4],[5]]) # this is a 2d array 
print(b)
print(type(b))
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
<class 'numpy.ndarray'>
(5, 1)


In [9]:
c = np.array([[1,2,3], [4,5,6]])
print(c)
print(c.shape)
print(c[1][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [10]:
# create arrays of zeros
a = np.zeros((3,3))  # inside the function, we are giving the shape
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# create arrays of ones
b = np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
# create array of some constants
# the first paramter is tuple which denotes the shape of the array
# the second paramter is what value it should take, the constant that should be there in the array
c = np.full((3,2), 5)
print(c)

[[5 5]
 [5 5]
 [5 5]]


In [13]:
# create identity matrix which is a square matrix
# we have to give the size to the function
d = np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
# to get a matrix of random integers
# we give a tuple of shape
randomMatrix = np.random.random((2,3))
print(randomMatrix)

[[0.9233067  0.61713384 0.46549971]
 [0.6884465  0.48380151 0.78625064]]


In [15]:
# we can also access and update elements of matrix
# if we want to print elements of a column, 
# we have to specify the indexing for each of the dimensions
print(randomMatrix[:,1])
# to print 2nd column of randomMatrix
# we need all the rows, so : -> no start value, no end value

[0.61713384 0.48380151]


In [16]:
# to update some particular elements 
randomMatrix[1, 1:] = 1
print(randomMatrix)
# in slicing(:), starting point is included and ending point is excluded

[[0.9233067  0.61713384 0.46549971]
 [0.6884465  1.         1.        ]]


In [22]:
# set some rows and columns with any values
z = np.zeros((3,3))
print(z)
z[1,:] = 5
z[:,-1] = 7
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


In [4]:
# to generate an array in a given range 
a = np.arange(10)
print(a)
# we will get all the numbers from 0 to 9

[0 1 2 3 4 5 6 7 8 9]


In [5]:
a = np.arange(10) + 5
print(a)
# array will start from 5

[ 5  6  7  8  9 10 11 12 13 14]


#### Data types

In [23]:
# all numpy arrays have some data types 
print(z.dtype)

float64


In [24]:
# to create an array of integers
m = np.zeros((3,3), dtype = np.int64)
print(m)
# by default dtype is float

[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### Mathematical Operations

In [25]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

- element wise addition

In [27]:
print(x+y)
# or
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


- element wise subtraction

In [28]:
print(x-y)
# or
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


- element wise multiplication

In [29]:
print(x*y)
# or
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


- element wise division

In [30]:
print(x/y)
# or
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


- element wise square root of a matrix

In [31]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


- matrix multiplication / dot product

In [32]:
print(x)
print(y)

print(x.dot(y))
# or
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


- multiplication / dot product of two vectors (vector can be treated as a linear array) gives a scalar

In [33]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))

30


- sum of all the elements of a matrix

In [34]:
print(a)
print(sum(a))

[1 2 3 4]
10


In [35]:
print(x)
print(np.sum(x))

[[1 2]
 [3 4]]
10


In [37]:
# np.sum() function takes an optional parameter axis
print(np.sum(x,axis=0))   # sum of all the columns
print(np.sum(x,axis=1))   # sum of all the rows

[4 6]
[3 7]


#### Stacking of arrays

In [38]:
print(a)
b = b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [47]:
# stack function is used to combine arrays to a single array
# firts we give the arrays we want to concatenate and 
# then the axix along which we want to concantenate
p = np.stack((a,b),axis=1)
# first array becomes the first column and second array becomes the second column
print(p)

[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]


In [43]:
q = np.stack((a,b),axis=0)
# first array becomes the first row and second array becomes the second row
print(q)

[[ 1  2  3  4]
 [ 1  4  9 16]]


#### Reshape a Numpy array

In [49]:
print(q)
q = q.reshape((4,2))  # here we give a new shape (4,2) to change the shape to 4 rows and 2 columns
print(q)

[[ 1  2  3  4]
 [ 1  4  9 16]]
[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


In [51]:
q = q.reshape((8,1))  
print(q)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 1]
 [ 4]
 [ 9]
 [16]]


In [52]:
# linear array
q = q.reshape((8,))  
print(q)

[ 1  2  3  4  1  4  9 16]


In [53]:
# if we need 4 rows/columns but we do not know the number of columns/rows respectively, 
# we can add -1 and it will automatically figure out what number of columns/rows should be there
q = q.reshape((4,-1))  
print(q)
q = q.reshape((-1,4))  
print(q)

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]
[[ 1  2  3  4]
 [ 1  4  9 16]]


### Numpy Random Module
- rand : Random values in a given shape.
- randn : Returns a sample (or samples) from the "standard normal" distribution.
- randint : Returns random integers from low (inclusive) to high (exclusive).
- random : Returns random floats in the half-open interval [0.0, 1.0]
- choice : Generates a random sample from a given 1-D array
- shuffle : shuffles the contents of a sequence

In [6]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [17]:
# setting a seed to have the same random numbers
np.random.seed(1)

# to shuffle all the elements of an array randomly
np.random.shuffle(a)
print(a)

[6 5 9]


In [10]:
# to generate an array of random numbers
a = np.random.rand(2,3)   # in the function, we give the shape
print(a)

[[0.27482931 0.53416677 0.71659121]
 [0.7448019  0.81113224 0.86311897]]


In [11]:
# to generate a random array of numbers from standard normal distribution
a = np.random.randn(2,3)   # in the function, we give the shape
print(a)

[[ 0.15633836  0.09228813  0.27305258]
 [-0.55932168 -0.36267299  2.27020131]]


In [12]:
# we will get 3 random integers in the range of 5 to 10
a = np.random.randint(5,10,3)
print(a)

[6 9 5]


In [13]:
# to randomly pick one element from the array
element = np.random.choice([1,4,3,2,11,27])    # here we give a list
print(element)

2


### Some more Numpy functions - Statistics
- min, max
- mean
- median
- average
- variance
- standard deviation

In [52]:
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)

[[1 2 3 4]
 [7 6 2 0]]


In [53]:
# finds the minimum element across all in the array
print(np.min(a))

# compute minimum element along each direction
print(np.min(a,axis=0))
print(np.min(a,axis=1))
# in case of multidimensional array, 
# we can specify the axis for the direction along which we want to do the computation

0
[1 2 2 0]
[1 0]


In [63]:
b = np.array([1,2,3,4,5])
# mean is used to average all the elements
# first way
m = sum(b)/5
print(m)
# second way
print(np.mean(b))

3.0
3.0


In [65]:
print(np.mean(a,axis = 0))   # along the columns
print(np.mean(a,axis = 1))   # along the rows 

[4.  4.  2.5 2. ]
[2.5  3.75]


In [66]:
# meadian is the middle most value
c = np.array([1,5,4,2,0])
print(np.median(c))

2.0


- there is a difference between mean and average (average is weighted average) 
- if array is [1,2,3,4] => mean = 10/4 = 2.5
- if array is [1,2,3,4] and weight is [1,2,3,4], each element is multiplied by its weight w[i],  
  so average = (1X1 + 2X2 + 3X3 + 4X4)/4 = 7.5

In [68]:
w = np.array([1,2,3,4,5])
print(np.average(c,weights=w))

2.066666666666667


In [69]:
# if weights are 1, average will the give the same result as mean
w = np.array([1,1,1,1,1])
print(np.average(c,weights=w))

2.4


In [74]:
# standard deviation
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))    # not using inbuilt function of standard deviation
print(myStd)

print(np.std(c))   # inbuilt function

1.854723699099141
1.854723699099141


In [75]:
# variance
print(myStd**2)
print(np.var(c))

3.440000000000001
3.4400000000000004
